<x-layouts.email.app>
    <div class="header" style="text-align: center; padding: 25px 0; background-color: #f8f9fa;">
        {{-- <img src="{{ $message->embed(public_path('images/logo-secondary.png')) }}" alt="{{ config('app.name') }}" style="height: 70px;"> --}}
    </div>

    <div class="content" style="max-width: 600px; margin: 0 auto; font-family: 'Segoe UI', Helvetica, Arial, sans-serif; padding: 25px;">
        <div style="text-align: center; margin-bottom: 25px;">
            <h1 style="color: #2e7d32; font-size: 22px; margin: 0; display: inline-block; padding: 8px 20px; background-color: #e8f5e9; border-radius: 4px; border-left: 4px solid #2e7d32;">
                Scholar Sponsor Extended
            </h1>
        </div>

        <div style="background-color: #ffffff; padding: 20px; border-radius: 8px; margin-bottom: 25px; border: 1px solid #e0e0e0; box-shadow: 0 2px 10px rgba(0,0,0,0.05);">

            <div style="display: flex; margin-bottom: 15px; align-items: center;">
                <div style="flex: 0 0 120px; font-weight: 600; color: #555;">Scholar Sponsor:</div>
                <div style="flex: 1; font-weight: 500; color: #d32f2f;">{{ $name }}</div>
            </div>
            
            <div style="display: flex; margin-bottom: 15px; align-items: center;">
                <div style="flex: 0 0 120px; font-weight: 600; color: #555;">Plan Type:</div>
                <div style="flex: 1; font-weight: 500; text-transform: capitalize; color: #1976d2;">{{ $planType }}</div>
            </div>
            
            <div style="display: flex; align-items: center;">
                <div style="flex: 0 0 120px; font-weight: 600; color: #555;">Amount Paid:</div>
                <div style="flex: 1; font-weight: 600; color: #2e7d32;">₱{{ number_format($amount, 2) }}</div>
            </div>
        </div>

        <div style="background-color: #e3f2fd; padding: 15px; border-radius: 8px; margin-bottom: 25px; border-left: 4px solid #1976d2;">
            <p style="margin: 0; font-size: 15px; color: #0d47a1;">
                This extension has been automatically processed and applied to the champion's account.
            </p>
        </div>

        <div style="margin-top: 30px; padding-top: 15px; border-top: 1px solid #f0f0f0; font-size: 13px; color: #757575; text-align: center;">
            <p style="margin: 5px 0;">This notification was automatically generated by the system.</p>
        </div>
    </div>
</x-layouts.email.app>