<x-layouts.email.app>

    <div class="header">
        {{-- <img src="{{ $message->embed(public_path('images/logo-secondary.png')) }}" alt="{{ config('app.name') }}" style="height: 80px;"> --}}
    </div>

    <div class="content">
        <div style="background-color: #e8f5e9; border-left: 4px solid #4CAF50; padding: 12px 16px; margin-bottom: 24px; border-radius: 0 4px 4px 0;">
            <p style="margin: 0; font-weight: 600; color: #2E7D32; display: flex; align-items: center;">
                <svg style="margin-right: 8px;" width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M12 2C6.48 2 2 6.48 2 12C2 17.52 6.48 22 12 22C17.52 22 22 17.52 22 12C22 6.48 17.52 2 12 2ZM10 17L5 12L6.41 10.59L10 14.17L17.59 6.58L19 8L10 17Z" fill="#4CAF50"/>
                </svg>
                If you've already made this payment, please ignore this notice. Thank you!
            </p>
        </div>

        <h1 style="color: #d32f2f; font-size: 20px; margin-bottom: 20px;">
            <span style="background-color: #ffebee; padding: 4px 8px; border-radius: 4px;">
                Hello, {{ $champion->first_name }}
            </span>
        </h1>

        <h2 style="font-size: 18px; color: #d32f2f; margin-bottom: 12px;">
            <strong>DUE PAYMENT NOTICE</strong>
        </h2>

        <div style="background-color: #e8f5e9; padding: 16px; border-radius: 8px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.05);">
            <p style="margin: 0; font-weight: 600;">Your Subscription Details:</p>
            <ul style="list-style: none; padding-left: 0; margin: 8px 0 0 0; font-size: 16px; line-height: 1.6;">
                <li><strong>Membership:</strong> {{ $data['membership'] }}</li>
                <li><strong>Payment Amount:</strong> <span style="color: #d32f2f;">₱{{ number_format($data['amount'], 2) }}</span></li>
                <li><strong>Plan Type:</strong> {{ ucfirst($data['plan_type']) }}</li>
                <li><strong>Payment Due:</strong> <span style="color: #d32f2f;">{{ $data['next_payment'] }}</span></li>
            </ul>
        </div>

        <div style="background-color: #f5f5f5; padding: 16px; border-radius: 8px; margin-bottom: 20px;">
            <p style="margin: 0; font-weight: 600;">
                It's time to renew your champion subscription. Click the button below to proceed with your payment:
            </p>
        </div>
        
        <div style="margin-top: 24px; text-align: center;">
            <p style="margin-bottom: 12px;">Quick Actions:</p>
            <a href="{{ $url }}" 
                style="display: inline-block; padding: 12px 30px; background-color: #d32f2f; color: white; text-decoration: none; border-radius: 4px; font-weight: bold; transition: background-color 0.3s;"
                onmouseover="this.style.backgroundColor='#b71c1c'" 
                onmouseout="this.style.backgroundColor='#d32f2f'">
                Pay Now
            </a>
        </div>

        <div style="margin-top: 32px; padding: 16px; background-color: #e3f2fd; border-radius: 8px;">
            <p style="margin-bottom: 4px; font-weight: 500;">Need a different plan?</p>
            <p style="margin-bottom: 12px; font-size: 14px; color: #555;">
                If the current plan doesn't meet your needs, you can choose a different subscription plan that suits you better.
            </p>
            <a href="{{ $data['change_plan_link'] }}" 
            style="
                display: inline-block;
                padding: 10px 20px;
                background-color: #1976d2;
                color: #ffffff;
                text-decoration: none;
                border-radius: 4px;
                font-weight: bold;
            ">
            Change Plan
            </a>
        </div>
        
        <div style="margin-top: 24px; font-size: 14px; color: #757575; padding-top: 16px; border-top: 1px solid #e0e0e0;">
            <p>This notification was automatically generated by the system.</p>
        </div>
    </div>

</x-layouts.email.app>