<x-layouts.email.app>
    <div class="header" style="text-align: center; padding: 25px 0; background-color: #f8f9fa; border-bottom: 1px solid #e0e0e0;">
        <img src="{{ $message->embed(public_path('images/logo-secondary.png')) }}" alt="{{ config('app.name') }}" style="height: 70px;">
    </div>

    <div class="content" style="max-width: 600px; margin: 0 auto; font-family: 'Segoe UI', Helvetica, Arial, sans-serif; padding: 25px;">
        <div style="text-align: center; margin-bottom: 25px;">
            <h1 style="color: #d32f2f; font-size: 22px; margin: 0; display: inline-block; padding: 8px 16px; background-color: #ffebee; border-radius: 30px; border-left: 4px solid #d32f2f;">
                New Champion Alert 
            </h1>
        </div>

        <div style="background-color: #ffffff; padding: 20px; border-radius: 8px; margin-bottom: 25px; border: 1px solid #e0e0e0; box-shadow: 0 2px 10px rgba(0,0,0,0.05);">
            <h2 style="color: #333; font-size: 18px; margin-top: 0; margin-bottom: 15px; padding-bottom: 8px; border-bottom: 1px solid #f0f0f0;">
                New Champion Registration
            </h2>
            
            <div style="display: flex; margin-bottom: 12px;">
                <div style="flex: 0 0 100px; font-weight: 600; color: #555;">Name:</div>
                <div style="flex: 1; font-weight: 500; color: #d32f2f;">{{ $name }}</div>
            </div>
            
            <div style="display: flex; margin-bottom: 12px;">
                <div style="flex: 0 0 100px; font-weight: 600; color: #555;">Plan:</div>
                <div style="flex: 1; font-weight: 500; text-transform: capitalize;">{{ $planType }}</div>
            </div>
            
            <div style="display: flex;">
                <div style="flex: 0 0 100px; font-weight: 600; color: #555;">Amount:</div>
                <div style="flex: 1; font-weight: 600; color: #2e7d32;">₱{{ number_format($amount, 2) }}</div>
            </div>
        </div>

        <div style="text-align: center; margin: 30px 0;">
            <a href="{{ config('app.url') }}/admin/champions" 
                style="display: inline-block; padding: 12px 30px; background-color: #d32f2f; color: white; text-decoration: none; border-radius: 30px; font-weight: bold; font-size: 16px; transition: all 0.3s; box-shadow: 0 2px 5px rgba(210, 47, 47, 0.3);"
                onmouseover="this.style.backgroundColor='#b71c1c'; this.style.transform='translateY(-2px)';"
                onmouseout="this.style.backgroundColor='#d32f2f'; this.style.transform='none';">
                View Champion Details
            </a>
        </div>

        <div style="margin-top: 35px; padding-top: 15px; border-top: 1px solid #f0f0f0; font-size: 13px; color: #757575; text-align: center;">
            <p style="margin: 5px 0;">This notification was automatically generated by the system.</p>
        </div>
    </div>
</x-layouts.email.app>