<x-layouts.email.app>

    <div class="header">
        <img src="{{ $message->embed(public_path('images/logo-secondary.png')) }}" alt="{{ config('app.name') }}" style="height: 80px;">
    </div>

    <div class="content">
        <h1 style="color: #d32f2f; font-size: 20px; margin-bottom: 20px;">
            <span style="background-color: #ffebee; padding: 4px 8px; border-radius: 4px;">
                New Champion Alert
            </span>
        </h1>

        <div style="background-color: #f5f5f5; padding: 16px; border-radius: 8px; margin-bottom: 20px;">
            <p style="margin: 0; font-weight: 600;">New Champion Registered:</p>
            <p style="margin: 8px 0 0 0; font-size: 18px;">
                <strong class="highlight">{{ $name }}</strong>
            </p>
        </div>
        
        <div style="margin-top: 24px;">
            <p style="margin-bottom: 12px;">Quick Actions:</p>
            <a href="{{ config('app.url') }}/admin/champions" 
               class="cta-button">
               View Details
            </a>
        </div>
        
        <div style="margin-top: 24px; font-size: 14px; color: #757575;">
            <p>This notification was automatically generated by the system.</p>
        </div>
    </div>

</x-layouts.email.app>

